import type { Lang } from "../../frontend/src/i18n";

// Hand-written Telegram bot copy. Every prompt and button is written per language (never machine-translated), so the bot
// is reliable in Hindi, Tamil and Telugu from the first message. {name} placeholders are filled by `say()`.

const en = {
  bookFreeOnly: "📅 Book {guide} only on {dates}",
  guideBookedDays: "✅ {guide} booked on {dates} — {cost}.",
  coverRest: "Add a guide for {dates}:",
  componentsLine: "Hotel, activities & transfers",
  btnDemo: "▶ Try the demo",
  demoIntro: "▶ <b>Demo trip:</b> New Delhi → Thanjavur · 28 Sept · 3 days · 4 travellers · Tamil guide.\nAfter the estimate, build the trip, pick a flight, then tap <b>Add a guide → Meera Novak</b> — she is busy on 28 Sept.",
  perPerson: "per person",
  catalogueFares: "ℹ️ Live fares are unavailable right now — showing catalogue fares.",
  welcome: "👋 <b>Welcome to PackagePro</b> — holiday packages priced live, with local guides who speak your language.\n\nनमस्ते · வணக்கம் · నమస్కారం\n\nChoose your language · भाषा चुनें · மொழியைத் தேர்ந்தெடுங்கள் · భాషను ఎంచుకోండి:",
  menu: "What would you like to do?",
  btnBrowse: "🧳 Browse packages", btnAi: "✨ Plan with AI", btnTrip: "📋 My trip", btnLang: "🌐 Language",
  aiPrompt: "Tell me what you want in your own words — e.g. “beach honeymoon under 40k” or “Mumbai to Goa for 3 days”. You can also send a voice note 🎙",
  slowDown: "You're sending a lot very quickly — please wait a few minutes, or use the buttons meanwhile.",
  voiceOff: "Voice notes need the speech service, which isn't set up here — please type instead.", voiceTooLong: "That voice note is a bit long — please keep it under 30 seconds.", voiceNotHeard: "Sorry, I couldn't make that out. Try again a little closer to the phone, or type it.", voiceHeard: "🎙 I heard:", voiceTip: "🎙 Tip: you can also send a voice note in English, हिन्दी, தமிழ் or తెలుగు.",
  pickTheme: "Pick a travel style:", mostBooked: "⭐ Most booked",
  packagesFor: "Top packages — tap one for details:",
  planThis: "🗓 Plan this trip", back: "⬅ Back",
  askOrigin: "🛫 Where are you flying from? Tap a city or type one.",
  askDate: "📅 Pick your departure date:",
  askDays: "🗓 How many days?",
  askTravellers: "👥 How many travellers?",
  askBudget: "💰 What's your total budget?", typeAmount: "✍️ Type an amount",
  askBudgetType: "Type your budget in rupees, e.g. 45000 or 45k.",
  askGuideLang: "🗣 Which language should your guide speak?",
  checking: "🔎 Checking live fares, the package, guides and what past travellers chose…",
  estimateTitle: "Your trip, estimated live",
  low: "Low", typical: "Typical", high: "High",
  verdict_comfortable: "✅ Your budget is comfortable", verdict_tight: "⚠️ Your budget is tight", verdict_unrealistic: "❌ Your budget falls short",
  cheapestFlight: "Cheapest live flight", packageDays: "Package for {days} days", guideFrom: "Guide in your language",
  noGuide: "No guide in this language for these dates",
  buildTrip: "✅ Build my trip", changeBudget: "💰 Change budget",
  pickFlight: "✈️ Pick your flight (live fares):",
  noFlights: "No flights found for this date — try another date.",
  yourPackage: "Your package", total: "Total", budgetLine: "Budget {budget} · {left} left",
  btnHotel: "🏨 Change hotel", btnAddons: "➕ Add-ons", btnGuide: "🧭 Add a guide", btnDays: "📅 Change days", btnReview: "✅ Review & confirm", btnRemoveGuide: "✖ Remove guide",
  pickHotel: "🏨 Choose a stay (price change vs current):", current: "current",
  pickAddon: "➕ Tap to add or remove:",
  pickGuide: "🧭 Guides who speak {lang} — each checked on every trip date:",
  guideAvail: "available all dates", guideBusy: "busy {dates}",
  noGuides: "No guides speak {lang} in {city}. Try another guide language from the menu.",
  refused: "❌ <b>{guide}</b> can't be booked — not available on <b>{dates}</b>.",
  substitute: "✅ Same language & specialisation: <b>{guide}</b> ({spec}, {where}) — {cost} ({delta} vs {old}).",
  newTotal: "New trip total: {old} → <b>{new}</b>",
  takeSub: "Book {guide}",
  noSubstitute: "No other guide with the same language and specialisation is free on those dates.",
  skipGuide: "Continue without a guide",
  guideBooked: "✅ {guide} booked for {days} days — {cost}.",
  overBudget: "⚠️ This change goes over your budget by <b>{amount}</b>. What would you like to do?",
  ngApprove: "Approve the extra amount", ngSwap: "Keep it as it was", ngRemove: "Drop this change", ngRaise: "Raise my budget",
  fx_auto: "✨ Fit my budget", fx_flight: "✈️ Cheaper flight", fx_hotel: "🏨 Cheaper stay", fx_experience: "🎟 Cheaper activity", fx_transfer: "🚗 Cheaper transfer", fx_meal: "🍽 Cheaper meal", fx_entry_ticket: "🎫 Cheaper tickets", fx_addon: "➖ Drop add-on", fx_guide: "🧭 Skip guide", fx_days: "📅 One day shorter", fxFits: "fits", fxIntro: "Tap a way to fit your budget — each is priced on the whole plan:",
  askNewCap: "Type your new total budget, e.g. 60000.",
  review: "🧾 Review your trip", confirm: "✅ Confirm booking", edit: "✏️ Keep editing",
  confirmed: "🎉 <b>Booked!</b> Your PNR is <b>{pnr}</b>.",
  openWeb: "🌐 Open on the web (PDF quotation)",
  noTrip: "You don't have a trip yet. Browse packages or tell me where you want to go.",
  error: "Sorry, something went wrong. Please try again.",
  updated: "✅ Updated — total now <b>{total}</b> ({delta}).",
  langSet: "Language set to English.",
  daysN: "{n} days", nonstop: "non-stop", stops: "{n} stop",
  flight: "Flight", hotel: "Stay", guide: "Guide", addOns: "Add-ons", swaps: "Your swaps", packageBase: "Package", day: "Day",
  help: "Commands: /menu · /packages · /plan · /trip · /language · /reset",
  gotIt: "Got it:",
  typeOrigin: "I couldn't find that city — please pick one from the list.",
  budgetInvalid: "Please type an amount in rupees, e.g. 45000.",
  pastDate: "Please pick today or a later date.",
  highlights: "Highlights", includes: "Includes", bookings: "{n} bookings",
  buildSuggestion: "🧳 {name}",
  sameCity: "same city", kmAway: "{km} km away",
};

type Copy = typeof en;

const hi: Copy = {
  bookFreeOnly: "📅 {guide} को केवल {dates} को बुक करें",
  guideBookedDays: "✅ {guide} {dates} के लिए बुक — {cost}।",
  coverRest: "{dates} के लिए गाइड जोड़ें:",
  componentsLine: "होटल, गतिविधियाँ और ट्रांसफ़र",
  btnDemo: "▶ डेमो आज़माएँ",
  demoIntro: "▶ <b>डेमो यात्रा:</b> नई दिल्ली → तंजावुर · 28 सितंबर · 3 दिन · 4 यात्री · तमिल गाइड।\nअनुमान के बाद यात्रा बनाएँ, उड़ान चुनें, फिर <b>गाइड जोड़ें → मीरा नोवाक</b> पर टैप करें — वे 28 सितंबर को व्यस्त हैं।",
  perPerson: "प्रति व्यक्ति",
  catalogueFares: "ℹ️ अभी लाइव किराए उपलब्ध नहीं हैं — कैटलॉग किराए दिखाए जा रहे हैं।",
  welcome: en.welcome,
  menu: "आप क्या करना चाहेंगे?",
  btnBrowse: "🧳 पैकेज देखें", btnAi: "✨ AI से प्लान करें", btnTrip: "📋 मेरी यात्रा", btnLang: "🌐 भाषा",
  aiPrompt: "अपने शब्दों में बताइए आप क्या चाहते हैं — जैसे “40 हज़ार में बीच हनीमून” या “मुंबई से गोवा 3 दिन के लिए”।",
  slowDown: "आप बहुत जल्दी-जल्दी भेज रहे हैं — कृपया कुछ मिनट रुकें, या तब तक बटन इस्तेमाल करें।",
  voiceOff: "वॉइस नोट के लिए स्पीच सेवा यहाँ सेट नहीं है — कृपया टाइप करें।", voiceTooLong: "वॉइस नोट थोड़ा लंबा है — कृपया 30 सेकंड से कम रखें।", voiceNotHeard: "माफ़ कीजिए, मैं समझ नहीं पाया। फ़ोन के थोड़ा पास बोलें या टाइप करें।", voiceHeard: "🎙 मैंने सुना:", voiceTip: "🎙 आप English, हिन्दी, தமிழ் या తెలుగు में वॉइस नोट भी भेज सकते हैं।",
  pickTheme: "यात्रा का अंदाज़ चुनें:", mostBooked: "⭐ सबसे ज़्यादा बुक",
  packagesFor: "टॉप पैकेज — विवरण के लिए किसी एक पर टैप करें:",
  planThis: "🗓 यह यात्रा प्लान करें", back: "⬅ वापस",
  askOrigin: "🛫 आप कहाँ से उड़ान भरेंगे? कोई शहर चुनें या लिखें।",
  askDate: "📅 प्रस्थान की तारीख चुनें:",
  askDays: "🗓 कितने दिन?",
  askTravellers: "👥 कितने यात्री?",
  askBudget: "💰 आपका कुल बजट कितना है?", typeAmount: "✍️ राशि लिखें",
  askBudgetType: "अपना बजट रुपये में लिखें, जैसे 45000 या 45k।",
  askGuideLang: "🗣 आपका गाइड कौन-सी भाषा बोले?",
  checking: "🔎 लाइव किराए, पैकेज, गाइड और पिछले यात्रियों की पसंद देख रहे हैं…",
  estimateTitle: "आपकी यात्रा का लाइव अनुमान",
  low: "न्यूनतम", typical: "सामान्य", high: "अधिकतम",
  verdict_comfortable: "✅ बजट आरामदायक है", verdict_tight: "⚠️ बजट थोड़ा तंग है", verdict_unrealistic: "❌ बजट कम पड़ रहा है",
  cheapestFlight: "सबसे सस्ती लाइव उड़ान", packageDays: "{days} दिन का पैकेज", guideFrom: "आपकी भाषा में गाइड",
  noGuide: "इन तारीखों पर इस भाषा का कोई गाइड नहीं",
  buildTrip: "✅ मेरी यात्रा बनाएँ", changeBudget: "💰 बजट बदलें",
  pickFlight: "✈️ अपनी उड़ान चुनें (लाइव किराए):",
  noFlights: "इस तारीख के लिए कोई उड़ान नहीं मिली — कोई और तारीख आज़माएँ।",
  yourPackage: "आपका पैकेज", total: "कुल", budgetLine: "बजट {budget} · शेष {left}",
  btnHotel: "🏨 होटल बदलें", btnAddons: "➕ ऐड-ऑन", btnGuide: "🧭 गाइड जोड़ें", btnDays: "📅 दिन बदलें", btnReview: "✅ समीक्षा और पुष्टि", btnRemoveGuide: "✖ गाइड हटाएँ",
  pickHotel: "🏨 ठहरने की जगह चुनें (मौजूदा से कीमत में अंतर):", current: "मौजूदा",
  pickAddon: "➕ जोड़ने या हटाने के लिए टैप करें:",
  pickGuide: "🧭 {lang} बोलने वाले गाइड — हर तारीख की उपलब्धता जाँची गई:",
  guideAvail: "सभी तारीखों पर उपलब्ध", guideBusy: "{dates} को व्यस्त",
  noGuides: "{city} में {lang} बोलने वाला कोई गाइड नहीं है। मेन्यू से कोई और गाइड भाषा चुनें।",
  refused: "❌ <b>{guide}</b> को बुक नहीं किया जा सकता — <b>{dates}</b> को उपलब्ध नहीं।",
  substitute: "✅ वही भाषा और विशेषज्ञता: <b>{guide}</b> ({spec}, {where}) — {cost} ({old} की तुलना में {delta})।",
  newTotal: "यात्रा का नया कुल: {old} → <b>{new}</b>",
  takeSub: "{guide} को बुक करें",
  noSubstitute: "उन तारीखों पर उसी भाषा और विशेषज्ञता वाला कोई दूसरा गाइड खाली नहीं है।",
  skipGuide: "बिना गाइड आगे बढ़ें",
  guideBooked: "✅ {guide} {days} दिन के लिए बुक — {cost}।",
  overBudget: "⚠️ इस बदलाव से बजट <b>{amount}</b> से ज़्यादा हो रहा है। आप क्या करना चाहेंगे?",
  ngApprove: "अतिरिक्त राशि स्वीकार करें", ngSwap: "पहले जैसा रखें", ngRemove: "यह बदलाव छोड़ें", ngRaise: "बजट बढ़ाएँ",
  fx_auto: "✨ अपने-आप बजट में लाएँ", fx_flight: "✈️ सस्ती फ़्लाइट", fx_hotel: "🏨 सस्ता ठहराव", fx_experience: "🎟 सस्ती गतिविधि", fx_transfer: "🚗 सस्ता ट्रांसफ़र", fx_meal: "🍽 सस्ता भोजन", fx_entry_ticket: "🎫 सस्ते टिकट", fx_addon: "➖ ऐड-ऑन हटाएँ", fx_guide: "🧭 गाइड न लें", fx_days: "📅 एक दिन कम", fxFits: "बजट में", fxIntro: "बजट में लाने का तरीका चुनें — हर विकल्प पूरी योजना पर गिना गया है:",
  askNewCap: "अपना नया कुल बजट लिखें, जैसे 60000।",
  review: "🧾 अपनी यात्रा की समीक्षा करें", confirm: "✅ बुकिंग की पुष्टि करें", edit: "✏️ बदलाव जारी रखें",
  confirmed: "🎉 <b>बुकिंग हो गई!</b> आपका PNR <b>{pnr}</b> है।",
  openWeb: "🌐 वेब पर खोलें (PDF कोटेशन)",
  noTrip: "अभी आपकी कोई यात्रा नहीं है। पैकेज देखें या बताइए आप कहाँ जाना चाहते हैं।",
  error: "माफ़ कीजिए, कुछ गड़बड़ हो गई। कृपया फिर से कोशिश करें।",
  updated: "✅ अपडेट हुआ — अब कुल <b>{total}</b> ({delta})।",
  langSet: "भाषा हिन्दी कर दी गई है।",
  daysN: "{n} दिन", nonstop: "नॉन-स्टॉप", stops: "{n} स्टॉप",
  flight: "उड़ान", hotel: "ठहराव", guide: "गाइड", addOns: "ऐड-ऑन", swaps: "आपके बदलाव", packageBase: "पैकेज", day: "दिन",
  help: "कमांड: /menu मेन्यू · /packages पैकेज · /plan AI प्लान · /trip मेरी यात्रा · /language भाषा · /reset नई शुरुआत",
  gotIt: "समझ गया:",
  typeOrigin: "यह शहर नहीं मिला — कृपया सूची से चुनें।",
  budgetInvalid: "कृपया रुपये में राशि लिखें, जैसे 45000।",
  pastDate: "कृपया आज या उसके बाद की तारीख चुनें।",
  highlights: "मुख्य आकर्षण", includes: "शामिल", bookings: "{n} बुकिंग",
  buildSuggestion: "🧳 {name}",
  sameCity: "उसी शहर में", kmAway: "{km} किमी दूर",
};

const ta: Copy = {
  bookFreeOnly: "📅 {guide} அவர்களை {dates} அன்று மட்டும் முன்பதிவு செய்",
  guideBookedDays: "✅ {guide} {dates} அன்று முன்பதிவு செய்யப்பட்டார் — {cost}.",
  coverRest: "{dates} அன்றுக்கு ஒரு வழிகாட்டியைச் சேர்க்கவும்:",
  componentsLine: "ஹோட்டல், செயல்பாடுகள் & போக்குவரத்து",
  btnDemo: "▶ டெமோவை முயற்சிக்கவும்",
  demoIntro: "▶ <b>டெமோ பயணம்:</b> புது தில்லி → தஞ்சாவூர் · 28 செப்டம்பர் · 3 நாட்கள் · 4 பயணிகள் · தமிழ் வழிகாட்டி.\nமதிப்பீட்டுக்குப் பிறகு பயணத்தை உருவாக்கி, விமானத்தைத் தேர்ந்தெடுத்து, <b>வழிகாட்டியைச் சேர் → மீரா நோவாக்</b> என்பதைத் தட்டவும் — அவர் 28 செப்டம்பர் அன்று கிடைக்கமாட்டார்.",
  perPerson: "ஒருவருக்கு",
  catalogueFares: "ℹ️ நேரடி கட்டணங்கள் இப்போது கிடைக்கவில்லை — பட்டியல் கட்டணங்கள் காட்டப்படுகின்றன.",
  welcome: en.welcome,
  menu: "நீங்கள் என்ன செய்ய விரும்புகிறீர்கள்?",
  btnBrowse: "🧳 தொகுப்புகளைப் பார்க்க", btnAi: "✨ AI உடன் திட்டமிட", btnTrip: "📋 என் பயணம்", btnLang: "🌐 மொழி",
  aiPrompt: "உங்களுக்கு என்ன வேண்டும் என்று உங்கள் வார்த்தைகளில் சொல்லுங்கள் — உதா. “40 ஆயிரத்தில் கடற்கரை தேனிலவு” அல்லது “மும்பையிலிருந்து கோவா 3 நாட்கள்”.",
  slowDown: "நீங்கள் மிக வேகமாக அனுப்புகிறீர்கள் — சில நிமிடங்கள் காத்திருங்கள், அல்லது அதுவரை பொத்தான்களைப் பயன்படுத்துங்கள்.",
  voiceOff: "குரல் செய்திக்கான பேச்சு சேவை இங்கு அமைக்கப்படவில்லை — தயவுசெய்து தட்டச்சு செய்யுங்கள்.", voiceTooLong: "குரல் செய்தி சற்று நீளமாக உள்ளது — 30 விநாடிகளுக்குள் வைக்கவும்.", voiceNotHeard: "மன்னிக்கவும், புரியவில்லை. தொலைபேசிக்கு அருகில் மீண்டும் பேசுங்கள் அல்லது தட்டச்சு செய்யுங்கள்.", voiceHeard: "🎙 நான் கேட்டது:", voiceTip: "🎙 English, हिन्दी, தமிழ் அல்லது తెలుగు மொழியில் குரல் செய்தியும் அனுப்பலாம்.",
  pickTheme: "பயண வகையைத் தேர்ந்தெடுங்கள்:", mostBooked: "⭐ அதிகம் முன்பதிவானவை",
  packagesFor: "சிறந்த தொகுப்புகள் — விவரங்களுக்கு ஒன்றைத் தட்டவும்:",
  planThis: "🗓 இந்தப் பயணத்தைத் திட்டமிடு", back: "⬅ பின்செல்",
  askOrigin: "🛫 எங்கிருந்து புறப்படுகிறீர்கள்? ஒரு நகரத்தைத் தட்டவும் அல்லது தட்டச்சு செய்யவும்.",
  askDate: "📅 புறப்படும் தேதியைத் தேர்ந்தெடுங்கள்:",
  askDays: "🗓 எத்தனை நாட்கள்?",
  askTravellers: "👥 எத்தனை பயணிகள்?",
  askBudget: "💰 உங்கள் மொத்த பட்ஜெட் எவ்வளவு?", typeAmount: "✍️ தொகையைத் தட்டச்சு செய்",
  askBudgetType: "உங்கள் பட்ஜெட்டை ரூபாயில் தட்டச்சு செய்யுங்கள், உதா. 45000 அல்லது 45k.",
  askGuideLang: "🗣 உங்கள் வழிகாட்டி எந்த மொழியில் பேச வேண்டும்?",
  checking: "🔎 நேரடி கட்டணங்கள், தொகுப்பு, வழிகாட்டிகள் மற்றும் முந்தைய பயணிகளின் தேர்வுகளைச் சரிபார்க்கிறோம்…",
  estimateTitle: "உங்கள் பயணத்தின் நேரடி மதிப்பீடு",
  low: "குறைந்தபட்சம்", typical: "வழக்கமானது", high: "அதிகபட்சம்",
  verdict_comfortable: "✅ பட்ஜெட் போதுமானது", verdict_tight: "⚠️ பட்ஜெட் சற்று நெருக்கமானது", verdict_unrealistic: "❌ பட்ஜெட் போதாது",
  cheapestFlight: "குறைந்த கட்டண நேரடி விமானம்", packageDays: "{days} நாள் தொகுப்பு", guideFrom: "உங்கள் மொழியில் வழிகாட்டி",
  noGuide: "இந்தத் தேதிகளில் இந்த மொழியில் வழிகாட்டி இல்லை",
  buildTrip: "✅ என் பயணத்தை உருவாக்கு", changeBudget: "💰 பட்ஜெட்டை மாற்று",
  pickFlight: "✈️ உங்கள் விமானத்தைத் தேர்ந்தெடுங்கள் (நேரடி கட்டணங்கள்):",
  noFlights: "இந்தத் தேதிக்கு விமானங்கள் இல்லை — வேறு தேதியை முயற்சிக்கவும்.",
  yourPackage: "உங்கள் தொகுப்பு", total: "மொத்தம்", budgetLine: "பட்ஜெட் {budget} · மீதம் {left}",
  btnHotel: "🏨 ஹோட்டலை மாற்று", btnAddons: "➕ கூடுதல் சேர்க்கைகள்", btnGuide: "🧭 வழிகாட்டியைச் சேர்", btnDays: "📅 நாட்களை மாற்று", btnReview: "✅ சரிபார்த்து உறுதிசெய்", btnRemoveGuide: "✖ வழிகாட்டியை நீக்கு",
  pickHotel: "🏨 தங்குமிடத்தைத் தேர்ந்தெடுங்கள் (தற்போதையதுடன் விலை வேறுபாடு):", current: "தற்போதையது",
  pickAddon: "➕ சேர்க்க அல்லது நீக்கத் தட்டவும்:",
  pickGuide: "🧭 {lang} பேசும் வழிகாட்டிகள் — ஒவ்வொரு தேதியும் சரிபார்க்கப்பட்டது:",
  guideAvail: "அனைத்து தேதிகளிலும் கிடைப்பார்", guideBusy: "{dates} அன்று கிடைக்கமாட்டார்",
  noGuides: "{city} நகரில் {lang} பேசும் வழிகாட்டிகள் இல்லை. மெனுவிலிருந்து வேறு மொழியைத் தேர்ந்தெடுங்கள்.",
  refused: "❌ <b>{guide}</b> அவர்களை முன்பதிவு செய்ய முடியாது — <b>{dates}</b> அன்று கிடைக்கமாட்டார்.",
  substitute: "✅ அதே மொழி மற்றும் சிறப்புத்துறை: <b>{guide}</b> ({spec}, {where}) — {cost} ({old} உடன் ஒப்பிடுகையில் {delta}).",
  newTotal: "பயணத்தின் புதிய மொத்தம்: {old} → <b>{new}</b>",
  takeSub: "{guide} அவர்களை முன்பதிவு செய்",
  noSubstitute: "அந்தத் தேதிகளில் அதே மொழி மற்றும் சிறப்புத்துறை கொண்ட வேறு வழிகாட்டி இல்லை.",
  skipGuide: "வழிகாட்டி இல்லாமல் தொடர்",
  guideBooked: "✅ {guide} {days} நாட்களுக்கு முன்பதிவு செய்யப்பட்டார் — {cost}.",
  overBudget: "⚠️ இந்த மாற்றம் உங்கள் பட்ஜெட்டை <b>{amount}</b> மீறுகிறது. என்ன செய்ய விரும்புகிறீர்கள்?",
  ngApprove: "கூடுதல் தொகையை ஏற்கிறேன்", ngSwap: "முன்பு இருந்தபடியே வை", ngRemove: "இந்த மாற்றத்தை விடு", ngRaise: "பட்ஜெட்டை உயர்த்து",
  fx_auto: "✨ தானாக பட்ஜெட்டுக்குள்", fx_flight: "✈️ மலிவான விமானம்", fx_hotel: "🏨 மலிவான தங்குமிடம்", fx_experience: "🎟 மலிவான செயல்பாடு", fx_transfer: "🚗 மலிவான போக்குவரத்து", fx_meal: "🍽 மலிவான உணவு", fx_entry_ticket: "🎫 மலிவான டிக்கெட்டுகள்", fx_addon: "➖ கூடுதலை நீக்கு", fx_guide: "🧭 வழிகாட்டி வேண்டாம்", fx_days: "📅 ஒரு நாள் குறைவு", fxFits: "பட்ஜெட்டுக்குள்", fxIntro: "பட்ஜெட்டுக்குள் கொண்டுவர ஒரு வழியைத் தேர்வு செய்யுங்கள் — ஒவ்வொன்றும் முழு திட்டத்தின் மீது கணக்கிடப்பட்டது:",
  askNewCap: "உங்கள் புதிய மொத்த பட்ஜெட்டைத் தட்டச்சு செய்யுங்கள், உதா. 60000.",
  review: "🧾 உங்கள் பயணத்தைச் சரிபாருங்கள்", confirm: "✅ முன்பதிவை உறுதிசெய்", edit: "✏️ தொடர்ந்து மாற்று",
  confirmed: "🎉 <b>முன்பதிவு முடிந்தது!</b> உங்கள் PNR <b>{pnr}</b>.",
  openWeb: "🌐 இணையத்தில் திறக்க (PDF விலைப்பட்டியல்)",
  noTrip: "உங்களுக்கு இன்னும் பயணம் இல்லை. தொகுப்புகளைப் பாருங்கள் அல்லது எங்கு செல்ல வேண்டும் என்று சொல்லுங்கள்.",
  error: "மன்னிக்கவும், ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.",
  updated: "✅ புதுப்பிக்கப்பட்டது — இப்போது மொத்தம் <b>{total}</b> ({delta}).",
  langSet: "மொழி தமிழாக அமைக்கப்பட்டது.",
  daysN: "{n} நாட்கள்", nonstop: "நேரடி", stops: "{n} நிறுத்தம்",
  flight: "விமானம்", hotel: "தங்குமிடம்", guide: "வழிகாட்டி", addOns: "கூடுதல் சேர்க்கைகள்", swaps: "உங்கள் மாற்றங்கள்", packageBase: "தொகுப்பு", day: "நாள்",
  help: "கட்டளைகள்: /menu மெனு · /packages தொகுப்புகள் · /plan AI திட்டம் · /trip என் பயணம் · /language மொழி · /reset புதிதாகத் தொடங்கு",
  gotIt: "புரிந்தது:",
  typeOrigin: "அந்த நகரம் கிடைக்கவில்லை — பட்டியலிலிருந்து தேர்ந்தெடுங்கள்.",
  budgetInvalid: "தயவுசெய்து ரூபாயில் தொகையைத் தட்டச்சு செய்யுங்கள், உதா. 45000.",
  pastDate: "இன்று அல்லது அதற்குப் பிறகான தேதியைத் தேர்ந்தெடுங்கள்.",
  highlights: "சிறப்பம்சங்கள்", includes: "அடங்கியவை", bookings: "{n} முன்பதிவுகள்",
  buildSuggestion: "🧳 {name}",
  sameCity: "அதே நகரம்", kmAway: "{km} கி.மீ. தொலைவில்",
};

const te: Copy = {
  bookFreeOnly: "📅 {guide} ను {dates} న మాత్రమే బుక్ చేయండి",
  guideBookedDays: "✅ {guide} {dates} న బుక్ అయ్యారు — {cost}.",
  coverRest: "{dates} కోసం ఒక గైడ్‌ను జోడించండి:",
  componentsLine: "హోటల్, కార్యకలాపాలు & ట్రాన్స్‌ఫర్లు",
  btnDemo: "▶ డెమో ప్రయత్నించండి",
  demoIntro: "▶ <b>డెమో ప్రయాణం:</b> న్యూ ఢిల్లీ → తంజావూరు · 28 సెప్టెంబర్ · 3 రోజులు · 4 ప్రయాణికులు · తమిళ గైడ్.\nఅంచనా తర్వాత ప్రయాణాన్ని సిద్ధం చేసి, విమానాన్ని ఎంచుకుని, <b>గైడ్‌ను జోడించండి → మీరా నోవాక్</b> పై నొక్కండి — ఆమె 28 సెప్టెంబర్‌న అందుబాటులో లేరు.",
  perPerson: "ఒక్కరికి",
  catalogueFares: "ℹ️ ప్రస్తుతం లైవ్ ఛార్జీలు అందుబాటులో లేవు — కేటలాగ్ ఛార్జీలు చూపిస్తున్నాం.",
  welcome: en.welcome,
  menu: "మీరు ఏమి చేయాలనుకుంటున్నారు?",
  btnBrowse: "🧳 ప్యాకేజీలు చూడండి", btnAi: "✨ AI తో ప్లాన్ చేయండి", btnTrip: "📋 నా ప్రయాణం", btnLang: "🌐 భాష",
  aiPrompt: "మీకు ఏమి కావాలో మీ మాటల్లో చెప్పండి — ఉదా. “40 వేలలో బీచ్ హనీమూన్” లేదా “ముంబై నుండి గోవా 3 రోజులు”.",
  slowDown: "మీరు చాలా వేగంగా పంపుతున్నారు — కొన్ని నిమిషాలు ఆగండి, లేదా అంతవరకు బటన్లు వాడండి.",
  voiceOff: "వాయిస్ నోట్ కోసం స్పీచ్ సేవ ఇక్కడ సెట్ చేయలేదు — దయచేసి టైప్ చేయండి.", voiceTooLong: "వాయిస్ నోట్ కొంచెం పొడవుగా ఉంది — 30 సెకన్లలోపు ఉంచండి.", voiceNotHeard: "క్షమించండి, అర్థం కాలేదు. ఫోన్‌కు దగ్గరగా మళ్లీ మాట్లాడండి లేదా టైప్ చేయండి.", voiceHeard: "🎙 నేను విన్నది:", voiceTip: "🎙 English, हिन्दी, தமிழ் లేదా తెలుగులో వాయిస్ నోట్ కూడా పంపవచ్చు.",
  pickTheme: "ప్రయాణ శైలిని ఎంచుకోండి:", mostBooked: "⭐ ఎక్కువగా బుక్ చేసినవి",
  packagesFor: "టాప్ ప్యాకేజీలు — వివరాల కోసం ఒకదానిపై నొక్కండి:",
  planThis: "🗓 ఈ ప్రయాణాన్ని ప్లాన్ చేయండి", back: "⬅ వెనుకకు",
  askOrigin: "🛫 మీరు ఎక్కడి నుండి బయలుదేరుతున్నారు? ఒక నగరాన్ని నొక్కండి లేదా టైప్ చేయండి.",
  askDate: "📅 బయలుదేరే తేదీని ఎంచుకోండి:",
  askDays: "🗓 ఎన్ని రోజులు?",
  askTravellers: "👥 ఎంత మంది ప్రయాణికులు?",
  askBudget: "💰 మీ మొత్తం బడ్జెట్ ఎంత?", typeAmount: "✍️ మొత్తాన్ని టైప్ చేయండి",
  askBudgetType: "మీ బడ్జెట్‌ను రూపాయల్లో టైప్ చేయండి, ఉదా. 45000 లేదా 45k.",
  askGuideLang: "🗣 మీ గైడ్ ఏ భాష మాట్లాడాలి?",
  checking: "🔎 లైవ్ ఛార్జీలు, ప్యాకేజీ, గైడ్లు మరియు గత ప్రయాణికుల ఎంపికలను తనిఖీ చేస్తున్నాం…",
  estimateTitle: "మీ ప్రయాణానికి లైవ్ అంచనా",
  low: "కనిష్ఠం", typical: "సాధారణం", high: "గరిష్ఠం",
  verdict_comfortable: "✅ బడ్జెట్ సరిపోతుంది", verdict_tight: "⚠️ బడ్జెట్ కొంచెం తక్కువ", verdict_unrealistic: "❌ బడ్జెట్ సరిపోదు",
  cheapestFlight: "అతి తక్కువ లైవ్ విమాన ఛార్జీ", packageDays: "{days} రోజుల ప్యాకేజీ", guideFrom: "మీ భాషలో గైడ్",
  noGuide: "ఈ తేదీల్లో ఈ భాషలో గైడ్ లేరు",
  buildTrip: "✅ నా ప్రయాణాన్ని సిద్ధం చేయండి", changeBudget: "💰 బడ్జెట్ మార్చండి",
  pickFlight: "✈️ మీ విమానాన్ని ఎంచుకోండి (లైవ్ ఛార్జీలు):",
  noFlights: "ఈ తేదీకి విమానాలు దొరకలేదు — మరో తేదీ ప్రయత్నించండి.",
  yourPackage: "మీ ప్యాకేజీ", total: "మొత్తం", budgetLine: "బడ్జెట్ {budget} · మిగిలింది {left}",
  btnHotel: "🏨 హోటల్ మార్చండి", btnAddons: "➕ అదనపు సేవలు", btnGuide: "🧭 గైడ్‌ను జోడించండి", btnDays: "📅 రోజులు మార్చండి", btnReview: "✅ సమీక్షించి నిర్ధారించండి", btnRemoveGuide: "✖ గైడ్‌ను తొలగించండి",
  pickHotel: "🏨 బసను ఎంచుకోండి (ప్రస్తుతదానితో ధర తేడా):", current: "ప్రస్తుతం",
  pickAddon: "➕ జోడించడానికి లేదా తొలగించడానికి నొక్కండి:",
  pickGuide: "🧭 {lang} మాట్లాడే గైడ్లు — ప్రతి తేదీ తనిఖీ చేయబడింది:",
  guideAvail: "అన్ని తేదీల్లో అందుబాటులో", guideBusy: "{dates} న అందుబాటులో లేరు",
  noGuides: "{city} లో {lang} మాట్లాడే గైడ్లు లేరు. మెనూ నుండి మరో గైడ్ భాషను ఎంచుకోండి.",
  refused: "❌ <b>{guide}</b> ను బుక్ చేయలేము — <b>{dates}</b> న అందుబాటులో లేరు.",
  substitute: "✅ అదే భాష & ప్రత్యేకత: <b>{guide}</b> ({spec}, {where}) — {cost} ({old} తో పోలిస్తే {delta}).",
  newTotal: "ప్రయాణం కొత్త మొత్తం: {old} → <b>{new}</b>",
  takeSub: "{guide} ను బుక్ చేయండి",
  noSubstitute: "ఆ తేదీల్లో అదే భాష మరియు ప్రత్యేకత గల మరో గైడ్ అందుబాటులో లేరు.",
  skipGuide: "గైడ్ లేకుండా కొనసాగండి",
  guideBooked: "✅ {guide} {days} రోజులకు బుక్ అయ్యారు — {cost}.",
  overBudget: "⚠️ ఈ మార్పు మీ బడ్జెట్‌ను <b>{amount}</b> మించుతుంది. మీరు ఏమి చేయాలనుకుంటున్నారు?",
  ngApprove: "అదనపు మొత్తాన్ని అంగీకరించు", ngSwap: "మునుపటిలాగే ఉంచు", ngRemove: "ఈ మార్పును వదిలేయి", ngRaise: "బడ్జెట్ పెంచు",
  fx_auto: "✨ ఆటోమేటిక్‌గా బడ్జెట్‌లోకి", fx_flight: "✈️ చౌకైన విమానం", fx_hotel: "🏨 చౌకైన బస", fx_experience: "🎟 చౌకైన కార్యకలాపం", fx_transfer: "🚗 చౌకైన రవాణా", fx_meal: "🍽 చౌకైన భోజనం", fx_entry_ticket: "🎫 చౌకైన టికెట్లు", fx_addon: "➖ యాడ్-ఆన్ తీసివేయి", fx_guide: "🧭 గైడ్ వద్దు", fx_days: "📅 ఒక రోజు తక్కువ", fxFits: "బడ్జెట్‌లో", fxIntro: "బడ్జెట్‌లోకి తెచ్చే మార్గం ఎంచుకోండి — ప్రతిదీ మొత్తం ప్లాన్‌పై లెక్కించబడింది:",
  askNewCap: "మీ కొత్త మొత్తం బడ్జెట్‌ను టైప్ చేయండి, ఉదా. 60000.",
  review: "🧾 మీ ప్రయాణాన్ని సమీక్షించండి", confirm: "✅ బుకింగ్ నిర్ధారించండి", edit: "✏️ మార్పులు కొనసాగించండి",
  confirmed: "🎉 <b>బుకింగ్ పూర్తైంది!</b> మీ PNR <b>{pnr}</b>.",
  openWeb: "🌐 వెబ్‌లో తెరవండి (PDF కొటేషన్)",
  noTrip: "మీకు ఇంకా ప్రయాణం లేదు. ప్యాకేజీలు చూడండి లేదా మీరు ఎక్కడికి వెళ్లాలనుకుంటున్నారో చెప్పండి.",
  error: "క్షమించండి, ఏదో పొరపాటు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
  updated: "✅ నవీకరించబడింది — ఇప్పుడు మొత్తం <b>{total}</b> ({delta}).",
  langSet: "భాష తెలుగుకు మార్చబడింది.",
  daysN: "{n} రోజులు", nonstop: "నాన్-స్టాప్", stops: "{n} స్టాప్",
  flight: "విమానం", hotel: "బస", guide: "గైడ్", addOns: "అదనపు సేవలు", swaps: "మీ మార్పులు", packageBase: "ప్యాకేజీ", day: "రోజు",
  help: "ఆదేశాలు: /menu మెనూ · /packages ప్యాకేజీలు · /plan AI ప్లాన్ · /trip నా ప్రయాణం · /language భాష · /reset కొత్తగా ప్రారంభించు",
  gotIt: "అర్థమైంది:",
  typeOrigin: "ఆ నగరం దొరకలేదు — దయచేసి జాబితా నుండి ఎంచుకోండి.",
  budgetInvalid: "దయచేసి మొత్తాన్ని రూపాయల్లో టైప్ చేయండి, ఉదా. 45000.",
  pastDate: "దయచేసి ఈరోజు లేదా ఆ తర్వాతి తేదీని ఎంచుకోండి.",
  highlights: "ముఖ్యాంశాలు", includes: "చేరినవి", bookings: "{n} బుకింగ్‌లు",
  buildSuggestion: "🧳 {name}",
  sameCity: "అదే నగరం", kmAway: "{km} కి.మీ. దూరంలో",
};

const COPY: Record<Lang, Copy> = { "en-IN": en, hi, ta, te };
export type BotKey = keyof Copy;

/** Bot copy in `lang`, with {placeholders} filled from `vars`. */
export function say(lang: Lang, key: BotKey, vars: Record<string, string | number> = {}) {
  return (COPY[lang] ?? en)[key].replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? ""));
}
