// Writes data-model/schema.sql from a fresh app database, so the documented schema is exactly what the code creates.
// Usage: pnpm db:schema
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { spawnSync } from "node:child_process";

const file = path.join(mkdtempSync(path.join(tmpdir(), "packagepro-schema-")), "app.db");
const init = spawnSync("npx", ["tsx", "-e", "import('./server/appStore.ts').then(m => m.listBookings(1))"], { env: { ...process.env, PACKAGEPRO_APP_DB: file, TELEGRAM_BOT_DISABLED: "true" }, stdio: "inherit" });
if (init.status !== 0) process.exit(init.status ?? 1);
const db = new DatabaseSync(file, { readOnly: true });
const rows = db.prepare("SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE WHEN name LIKE 'app_%' OR name LIKE 'idx_app_%' THEN 1 ELSE 0 END, rowid").all();
const canonical = rows.filter(row => !row.name.startsWith("app_") && !row.name.startsWith("idx_app_"));
const additions = rows.filter(row => row.name.startsWith("app_") || row.name.startsWith("idx_app_"));
const out = [
  "-- PackagePro — application database schema (generated by `pnpm db:schema` from server/appStore.ts; do not edit by hand).",
  "--",
  "-- The PS-04 dataset itself (21 canonical tables, read-only) is data/PS-04.db with DDL in data/schema.sqlite.sql.",
  "-- This file is the READ-WRITE app database PackagePro creates next to it:",
  "--   1. Canonical tables it writes, created verbatim from data/schema.sqlite.sql (columns never renamed — rule R1),",
  "--      plus three R1-additive columns on bookings (contact_email, contact_phone, guide_id).",
  "--   2. PackagePro additions (app_*), documented in data-model/DATA_MODEL.md.",
  "",
  "-- ============================================================ 1. canonical tables (shared data model)",
  ...canonical.map(row => `${row.sql};\n`),
  "-- ============================================================ 2. PackagePro additions",
  ...additions.map(row => `${row.sql};\n`),
].join("\n");
writeFileSync("data-model/schema.sql", out);
console.log(`data-model/schema.sql: ${canonical.length} canonical + ${additions.length} addition statements`);
