import type { Lang } from "@/i18n";

// Hand-written copy for the printable quotation. Fixed wording (labels, letters, terms) never goes through live machine
// translation, so the PDF is fully in the chosen language on the first click and contractual lines stay exact.
// Keys are the English text; {city} is filled in by the caller.

export const QUOTE_EN: Record<string, string> = {
  LETTER_TRIP: "Thank you for planning with PackagePro. Here is your {city} holiday, customised by you and priced live, with every guide date checked.",
  LETTER_EST: "Here is our first estimate for {city}, built from live fares, the real package catalogue and what past travellers chose. Pick an option and we will customise it with you.",
};

export const QUOTE_COPY: Partial<Record<Lang, Record<string, string>>> = {
  hi: {
    "Package base": "पैकेज बेस", "per person": "प्रति व्यक्ति", "day-by-day plan": "दिन-वार योजना", "Check-out and departure": "चेक-आउट और वापसी",
    "Reference": "संदर्भ", "Booking": "बुकिंग",
    LETTER_TRIP: "PackagePro के साथ योजना बनाने के लिए धन्यवाद। यह रही आपकी {city} छुट्टी — आपकी पसंद से तैयार, लाइव कीमतों के साथ, और हर गाइड तारीख की जाँच के साथ।",
    LETTER_EST: "{city} के लिए यह हमारा पहला अनुमान है, जो लाइव किराए, असली पैकेज कैटलॉग और पिछले यात्रियों की पसंद पर आधारित है। एक विकल्प चुनें और हम आपके साथ उसे अनुकूलित करेंगे।",
    "AI planner": "एआई प्लानर", "Add-ons": "ऐड-ऑन", "Amount": "राशि", "Available all dates": "सभी तारीखों पर उपलब्ध", "Best fit": "सबसे उपयुक्त",
    "Budget": "बजट", "Busy": "व्यस्त", "Confirmed": "पुष्ट", "Day by day": "दिन-प्रतिदिन", "Day": "दिन", "Dear traveller,": "प्रिय यात्री,",
    "Departure": "प्रस्थान", "Duration": "अवधि", "Flight": "उड़ान", "Flights": "उड़ानें", "Guide": "गाइड", "Guides in your language": "आपकी भाषा में गाइड",
    "Included in the package": "पैकेज में शामिल", "Included": "शामिल", "Inclusions & exclusions": "शामिल और शामिल नहीं", "Inclusions": "क्या शामिल है",
    "Investment": "निवेश", "Item": "विवरण", "Live fares": "लाइव किराए", "Local guide": "स्थानीय गाइड", "Local guides": "स्थानीय गाइड",
    "Lowest live fare": "सबसे कम लाइव किराया", "Non-stop": "नॉन-स्टॉप", "Not included": "शामिल नहीं", "Option": "विकल्प",
    "Our take on this trip": "इस यात्रा पर हमारी राय", "PS-04 dataset, Google Flights and guide availability": "PS-04 डेटासेट, Google Flights और गाइड उपलब्धता",
    "Package": "पैकेज", "PackagePro travel desk": "PackagePro ट्रैवल डेस्क", "Past travellers": "पिछले यात्री", "Premium": "प्रीमियम",
    "Prices generated live on": "कीमतें लाइव तैयार की गईं:", "Quotation": "कोटेशन", "Ready to confirm": "पुष्टि के लिए तैयार", "Recommended": "अनुशंसित",
    "Schedule": "कार्यक्रम", "Star": "स्टार", "Stay": "ठहराव", "Total": "कुल", "Transport": "परिवहन", "Travel & stay": "यात्रा और ठहराव",
    "Travellers": "यात्री", "Typical fare": "सामान्य किराया", "Upgraded stay": "अपग्रेडेड ठहराव", "Value": "किफ़ायती",
    "We would be delighted to hold these arrangements for you.": "आपके लिए ये व्यवस्थाएँ करने में हमें खुशी होगी।",
    "What is covered": "क्या-क्या शामिल है", "What it includes": "इसमें क्या शामिल है", "What travellers loved": "यात्रियों को क्या पसंद आया",
    "Your accommodation options": "आपके ठहरने के विकल्प", "Your arrangements": "आपकी व्यवस्थाएँ", "Your budget": "आपका बजट",
    "Your package options": "आपके पैकेज विकल्प", "Your price": "आपकी कीमत", "Your swaps": "आपके बदलाव", "Hotel, activities & transfers": "होटल, गतिविधियाँ और ट्रांसफ़र", "all add-ons": "सभी ऐड-ऑन",
    "available on every date": "हर तारीख पर उपलब्ध", "average spend": "औसत खर्च", "bookings": "बुकिंग", "days": "दिन", "flights": "उड़ानें",
    "guide": "गाइड", "nights": "रातें", "package": "पैकेज", "past trips": "पिछली यात्राएँ", "remaining": "शेष", "stop": "स्टॉप",
    "Activity": "गतिविधि", "Transfer": "ट्रांसफ़र", "Meal": "भोजन", "Ticket": "टिकट",
    "Guide:": "गाइड:", "Check in:": "चेक-इन:", "Stay:": "ठहराव:", "Arrive on": "आगमन:",
    "Your budget is comfortable": "आपका बजट आरामदायक है", "Your budget is tight": "आपका बजट थोड़ा तंग है", "Your budget is unrealistic": "आपका बजट कम पड़ रहा है",
    "Accommodation, daily breakfast, private transfers, entry tickets where listed.": "आवास, रोज़ का नाश्ता, निजी ट्रांसफ़र, सूचीबद्ध जगहों के प्रवेश टिकट।",
    "Flights, personal expenses, anything not listed under inclusions.": "उड़ानें, निजी खर्च, शामिल सूची में न दी गई कोई भी चीज़।",
    "Fine print": "ज़रूरी जानकारी", "Terms & conditions": "नियम और शर्तें",
    "Flight fares are live at the time of this quotation and are confirmed only when ticketed.": "उड़ान किराए इस कोटेशन के समय के लाइव किराए हैं और टिकट जारी होने पर ही पक्के होते हैं।",
    "This is an indicative estimate. Flight fares are live and change until booked.": "यह एक अनुमानित राशि है। उड़ान किराए लाइव हैं और बुकिंग तक बदल सकते हैं।",
    "Guides are checked date by date against their calendar; an unavailable guide is never booked, and a same-language substitute is offered instead.": "हर तारीख के लिए गाइड का कैलेंडर जाँचा जाता है; अनुपलब्ध गाइड कभी बुक नहीं होता, उसकी जगह उसी भाषा का दूसरा गाइड सुझाया जाता है।",
    "Hotels, activities and transfers are subject to availability at confirmation.": "होटल, गतिविधियाँ और ट्रांसफ़र पुष्टि के समय उपलब्धता पर निर्भर हैं।",
    "Payment: 30% to confirm, balance 20 days before departure. Amendments are repriced live.": "भुगतान: पुष्टि के लिए 30%, बाकी राशि प्रस्थान से 20 दिन पहले। बदलावों की कीमत लाइव दोबारा तय होती है।",
    "Cancellation: free within 24 hours of booking; after that, supplier charges apply.": "रद्दीकरण: बुकिंग के 24 घंटे के भीतर मुफ़्त; उसके बाद सप्लायर शुल्क लागू होंगे।",
  },
  ta: {
    "Package base": "தொகுப்பு அடிப்படை", "per person": "ஒருவருக்கு", "day-by-day plan": "நாள்வாரித் திட்டம்", "Check-out and departure": "செக்-அவுட் மற்றும் திரும்புதல்",
    "Reference": "குறிப்பு எண்", "Booking": "முன்பதிவு",
    LETTER_TRIP: "PackagePro உடன் திட்டமிட்டதற்கு நன்றி. இதோ உங்கள் {city} விடுமுறை — நீங்களே தனிப்பயனாக்கியது, நேரடி விலைகளுடன், ஒவ்வொரு வழிகாட்டி தேதியும் சரிபார்க்கப்பட்டது.",
    LETTER_EST: "{city} பயணத்திற்கான எங்கள் முதல் மதிப்பீடு இது — நேரடி கட்டணங்கள், உண்மையான தொகுப்புப் பட்டியல் மற்றும் முந்தைய பயணிகளின் தேர்வுகளின் அடிப்படையில். ஒரு தேர்வைத் தேர்ந்தெடுங்கள், உங்களுடன் சேர்ந்து அதைத் தனிப்பயனாக்குவோம்.",
    "AI planner": "AI திட்டமிடுபவர்", "Add-ons": "கூடுதல் சேர்க்கைகள்", "Amount": "தொகை", "Available all dates": "அனைத்து தேதிகளிலும் கிடைக்கும்", "Best fit": "சிறந்த தேர்வு",
    "Budget": "பட்ஜெட்", "Busy": "கிடைக்காது", "Confirmed": "உறுதிசெய்யப்பட்டது", "Day by day": "நாள்வாரியாக", "Day": "நாள்", "Dear traveller,": "அன்புள்ள பயணியே,",
    "Departure": "புறப்பாடு", "Duration": "காலம்", "Flight": "விமானம்", "Flights": "விமானங்கள்", "Guide": "வழிகாட்டி", "Guides in your language": "உங்கள் மொழியில் வழிகாட்டிகள்",
    "Included in the package": "தொகுப்பில் அடங்கியவை", "Included": "அடங்கியவை", "Inclusions & exclusions": "அடங்கியவை & அடங்காதவை", "Inclusions": "அடங்கியவை",
    "Investment": "முதலீடு", "Item": "விவரம்", "Live fares": "நேரடி கட்டணங்கள்", "Local guide": "உள்ளூர் வழிகாட்டி", "Local guides": "உள்ளூர் வழிகாட்டிகள்",
    "Lowest live fare": "குறைந்த நேரடி கட்டணம்", "Non-stop": "நேரடி விமானம்", "Not included": "அடங்காதவை", "Option": "தேர்வு",
    "Our take on this trip": "இந்தப் பயணம் பற்றிய எங்கள் கருத்து", "PS-04 dataset, Google Flights and guide availability": "PS-04 தரவுத்தொகுப்பு, Google Flights மற்றும் வழிகாட்டி இருப்பு",
    "Package": "தொகுப்பு", "PackagePro travel desk": "PackagePro பயண மையம்", "Past travellers": "முந்தைய பயணிகள்", "Premium": "பிரீமியம்",
    "Prices generated live on": "விலைகள் நேரடியாக உருவாக்கப்பட்டது:", "Quotation": "விலைப்பட்டியல்", "Ready to confirm": "உறுதிப்படுத்தத் தயார்", "Recommended": "பரிந்துரைக்கப்பட்டது",
    "Schedule": "அட்டவணை", "Star": "நட்சத்திரம்", "Stay": "தங்குமிடம்", "Total": "மொத்தம்", "Transport": "போக்குவரத்து", "Travel & stay": "பயணம் & தங்குமிடம்",
    "Travellers": "பயணிகள்", "Typical fare": "வழக்கமான கட்டணம்", "Upgraded stay": "மேம்படுத்தப்பட்ட தங்குமிடம்", "Value": "சிக்கனம்",
    "We would be delighted to hold these arrangements for you.": "உங்களுக்காக இந்த ஏற்பாடுகளைச் செய்வதில் நாங்கள் மகிழ்ச்சியடைகிறோம்.",
    "What is covered": "எவை அடங்கும்", "What it includes": "இதில் அடங்கியவை", "What travellers loved": "பயணிகள் விரும்பியவை",
    "Your accommodation options": "உங்கள் தங்குமிடத் தேர்வுகள்", "Your arrangements": "உங்கள் ஏற்பாடுகள்", "Your budget": "உங்கள் பட்ஜெட்",
    "Your package options": "உங்கள் தொகுப்புத் தேர்வுகள்", "Your price": "உங்கள் விலை", "Your swaps": "உங்கள் மாற்றங்கள்", "Hotel, activities & transfers": "ஹோட்டல், செயல்பாடுகள் & போக்குவரத்து", "all add-ons": "அனைத்து கூடுதல் சேர்க்கைகள்",
    "available on every date": "ஒவ்வொரு தேதியிலும் கிடைக்கும்", "average spend": "சராசரி செலவு", "bookings": "முன்பதிவுகள்", "days": "நாட்கள்", "flights": "விமானங்கள்",
    "guide": "வழிகாட்டி", "nights": "இரவுகள்", "package": "தொகுப்பு", "past trips": "முந்தைய பயணங்கள்", "remaining": "மீதம்", "stop": "நிறுத்தம்",
    "Activity": "செயல்பாடு", "Transfer": "போக்குவரத்து", "Meal": "உணவு", "Ticket": "டிக்கெட்",
    "Guide:": "வழிகாட்டி:", "Check in:": "செக்-இன்:", "Stay:": "தங்குமிடம்:", "Arrive on": "வருகை:",
    "Your budget is comfortable": "உங்கள் பட்ஜெட் போதுமானது", "Your budget is tight": "உங்கள் பட்ஜெட் சற்று நெருக்கமானது", "Your budget is unrealistic": "உங்கள் பட்ஜெட் போதாது",
    "Accommodation, daily breakfast, private transfers, entry tickets where listed.": "தங்குமிடம், தினசரி காலை உணவு, தனியார் போக்குவரத்து, குறிப்பிட்ட இடங்களுக்கான நுழைவுச் சீட்டுகள்.",
    "Flights, personal expenses, anything not listed under inclusions.": "விமானக் கட்டணம், தனிப்பட்ட செலவுகள், அடங்கியவை பட்டியலில் இல்லாத அனைத்தும்.",
    "Fine print": "முக்கிய குறிப்புகள்", "Terms & conditions": "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
    "Flight fares are live at the time of this quotation and are confirmed only when ticketed.": "விமானக் கட்டணங்கள் இந்த விலைப்பட்டியல் உருவான நேரத்தின் நேரடி கட்டணங்கள்; டிக்கெட் வழங்கப்பட்ட பின்னரே உறுதியாகும்.",
    "This is an indicative estimate. Flight fares are live and change until booked.": "இது ஒரு தோராயமான மதிப்பீடு. விமானக் கட்டணங்கள் நேரடியானவை; முன்பதிவு செய்யும் வரை மாறக்கூடும்.",
    "Guides are checked date by date against their calendar; an unavailable guide is never booked, and a same-language substitute is offered instead.": "ஒவ்வொரு தேதிக்கும் வழிகாட்டியின் அட்டவணை சரிபார்க்கப்படுகிறது; கிடைக்காத வழிகாட்டி ஒருபோதும் முன்பதிவு செய்யப்படமாட்டார், அதற்குப் பதிலாக அதே மொழி பேசும் மாற்று வழிகாட்டி பரிந்துரைக்கப்படுவார்.",
    "Hotels, activities and transfers are subject to availability at confirmation.": "ஹோட்டல்கள், செயல்பாடுகள் மற்றும் போக்குவரத்து உறுதிப்படுத்தும் நேரத்தில் உள்ள இருப்பைப் பொறுத்தது.",
    "Payment: 30% to confirm, balance 20 days before departure. Amendments are repriced live.": "கட்டணம்: உறுதிப்படுத்த 30%, மீதித் தொகை புறப்படுவதற்கு 20 நாட்களுக்கு முன். மாற்றங்களுக்கு நேரடியாக மீண்டும் விலை கணக்கிடப்படும்.",
    "Cancellation: free within 24 hours of booking; after that, supplier charges apply.": "ரத்து: முன்பதிவு செய்த 24 மணி நேரத்திற்குள் இலவசம்; அதன் பிறகு சப்ளையர் கட்டணங்கள் பொருந்தும்.",
  },
  te: {
    "Package base": "ప్యాకేజీ బేస్", "per person": "ఒక్కరికి", "day-by-day plan": "రోజువారీ ప్లాన్", "Check-out and departure": "చెక్-అవుట్ మరియు తిరుగు ప్రయాణం",
    "Reference": "రిఫరెన్స్", "Booking": "బుకింగ్",
    LETTER_TRIP: "PackagePro తో ప్లాన్ చేసినందుకు ధన్యవాదాలు. ఇదిగో మీ {city} సెలవు ప్రయాణం — మీరే తీర్చిదిద్దినది, లైవ్ ధరలతో, ప్రతి గైడ్ తేదీ తనిఖీ చేయబడింది.",
    LETTER_EST: "{city} కోసం ఇది మా మొదటి అంచనా — లైవ్ ఛార్జీలు, నిజమైన ప్యాకేజీ జాబితా మరియు గత ప్రయాణికుల ఎంపికల ఆధారంగా. ఒక ఎంపికను ఎంచుకోండి, మీతో కలిసి దాన్ని తీర్చిదిద్దుతాం.",
    "AI planner": "AI ప్లానర్", "Add-ons": "అదనపు సేవలు", "Amount": "రుసుము", "Available all dates": "అన్ని తేదీల్లో అందుబాటులో", "Best fit": "ఉత్తమ ఎంపిక",
    "Budget": "బడ్జెట్", "Busy": "అందుబాటులో లేరు", "Confirmed": "నిర్ధారించబడింది", "Day by day": "రోజువారీ ప్రణాళిక", "Day": "రోజు", "Dear traveller,": "ప్రియమైన ప్రయాణికుడా,",
    "Departure": "బయలుదేరే తేదీ", "Duration": "వ్యవధి", "Flight": "విమానం", "Flights": "విమానాలు", "Guide": "గైడ్", "Guides in your language": "మీ భాషలో గైడ్లు",
    "Included in the package": "ప్యాకేజీలో చేరినవి", "Included": "చేరినవి", "Inclusions & exclusions": "చేరినవి & చేరనివి", "Inclusions": "చేరినవి",
    "Investment": "పెట్టుబడి", "Item": "వివరం", "Live fares": "లైవ్ ఛార్జీలు", "Local guide": "స్థానిక గైడ్", "Local guides": "స్థానిక గైడ్లు",
    "Lowest live fare": "అతి తక్కువ లైవ్ ఛార్జీ", "Non-stop": "నాన్-స్టాప్", "Not included": "చేరనివి", "Option": "ఎంపిక",
    "Our take on this trip": "ఈ ప్రయాణంపై మా అభిప్రాయం", "PS-04 dataset, Google Flights and guide availability": "PS-04 డేటాసెట్, Google Flights మరియు గైడ్ లభ్యత",
    "Package": "ప్యాకేజీ", "PackagePro travel desk": "PackagePro ట్రావెల్ డెస్క్", "Past travellers": "గత ప్రయాణికులు", "Premium": "ప్రీమియం",
    "Prices generated live on": "ధరలు లైవ్‌గా రూపొందించబడ్డాయి:", "Quotation": "కొటేషన్", "Ready to confirm": "నిర్ధారణకు సిద్ధం", "Recommended": "సిఫార్సు చేయబడింది",
    "Schedule": "షెడ్యూల్", "Star": "స్టార్", "Stay": "బస", "Total": "మొత్తం", "Transport": "రవాణా", "Travel & stay": "ప్రయాణం & బస",
    "Travellers": "ప్రయాణికులు", "Typical fare": "సాధారణ ఛార్జీ", "Upgraded stay": "అప్‌గ్రేడ్ చేసిన బస", "Value": "పొదుపు",
    "We would be delighted to hold these arrangements for you.": "మీ కోసం ఈ ఏర్పాట్లు చేయడం మాకు ఆనందంగా ఉంటుంది.",
    "What is covered": "ఏమేమి చేరి ఉన్నాయి", "What it includes": "ఇందులో ఏమున్నాయి", "What travellers loved": "ప్రయాణికులు ఇష్టపడినవి",
    "Your accommodation options": "మీ బస ఎంపికలు", "Your arrangements": "మీ ఏర్పాట్లు", "Your budget": "మీ బడ్జెట్",
    "Your package options": "మీ ప్యాకేజీ ఎంపికలు", "Your price": "మీ ధర", "Your swaps": "మీ మార్పులు", "Hotel, activities & transfers": "హోటల్, కార్యకలాపాలు & ట్రాన్స్‌ఫర్లు", "all add-ons": "అన్ని అదనపు సేవలు",
    "available on every date": "ప్రతి తేదీన అందుబాటులో", "average spend": "సగటు ఖర్చు", "bookings": "బుకింగ్‌లు", "days": "రోజులు", "flights": "విమానాలు",
    "guide": "గైడ్", "nights": "రాత్రులు", "package": "ప్యాకేజీ", "past trips": "గత ప్రయాణాలు", "remaining": "మిగిలింది", "stop": "స్టాప్",
    "Activity": "కార్యకలాపం", "Transfer": "ట్రాన్స్‌ఫర్", "Meal": "భోజనం", "Ticket": "టికెట్",
    "Guide:": "గైడ్:", "Check in:": "చెక్-ఇన్:", "Stay:": "బస:", "Arrive on": "రాక:",
    "Your budget is comfortable": "మీ బడ్జెట్ సరిపోతుంది", "Your budget is tight": "మీ బడ్జెట్ కొంచెం తక్కువగా ఉంది", "Your budget is unrealistic": "మీ బడ్జెట్ సరిపోదు",
    "Accommodation, daily breakfast, private transfers, entry tickets where listed.": "వసతి, రోజువారీ అల్పాహారం, ప్రైవేట్ ట్రాన్స్‌ఫర్లు, జాబితాలో ఉన్న ప్రవేశ టికెట్లు.",
    "Flights, personal expenses, anything not listed under inclusions.": "విమాన ఛార్జీలు, వ్యక్తిగత ఖర్చులు, చేరినవి జాబితాలో లేని ఏదైనా.",
    "Fine print": "ముఖ్య గమనికలు", "Terms & conditions": "నిబంధనలు మరియు షరతులు",
    "Flight fares are live at the time of this quotation and are confirmed only when ticketed.": "విమాన ఛార్జీలు ఈ కొటేషన్ సమయంలోని లైవ్ ధరలు; టికెట్ జారీ అయిన తర్వాతే ఖరారవుతాయి.",
    "This is an indicative estimate. Flight fares are live and change until booked.": "ఇది సూచనాత్మక అంచనా మాత్రమే. విమాన ఛార్జీలు లైవ్ ధరలు; బుకింగ్ వరకు మారవచ్చు.",
    "Guides are checked date by date against their calendar; an unavailable guide is never booked, and a same-language substitute is offered instead.": "ప్రతి తేదీకి గైడ్ క్యాలెండర్ తనిఖీ చేయబడుతుంది; అందుబాటులో లేని గైడ్‌ను ఎప్పుడూ బుక్ చేయము, బదులుగా అదే భాష మాట్లాడే మరో గైడ్‌ను సూచిస్తాము.",
    "Hotels, activities and transfers are subject to availability at confirmation.": "హోటళ్లు, కార్యకలాపాలు మరియు ట్రాన్స్‌ఫర్‌లు నిర్ధారణ సమయంలో లభ్యతకు లోబడి ఉంటాయి.",
    "Payment: 30% to confirm, balance 20 days before departure. Amendments are repriced live.": "చెల్లింపు: నిర్ధారణకు 30%, మిగిలిన మొత్తం బయలుదేరడానికి 20 రోజుల ముందు. మార్పులకు ధర లైవ్‌గా మళ్లీ లెక్కించబడుతుంది.",
    "Cancellation: free within 24 hours of booking; after that, supplier charges apply.": "రద్దు: బుకింగ్ చేసిన 24 గంటలలోపు ఉచితం; ఆ తర్వాత సరఫరాదారు ఛార్జీలు వర్తిస్తాయి.",
  },
};
